global:
  scrape_interval: 5s # How frequently to scrape targets by default.

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Assuming node_exporter is running on localhost:9100

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
